{
    'name': 'Chicken production',
    'version': '17.0',
    'summary': 'Chicken production',
    'description': 'Chicken production',
    'category': 'Manufacturing',
    'depends': ['stock', 'import_folder', 'maintenance', 'project'],
    'data': [
        'data/ir_sequence_data.xml',
        'security/ir.model.access.csv',
        'security/chicken_security.xml',
        'views/chick_configuration_views.xml',
        'views/chicken_building_views.xml',
        'views/production_phase_views.xml',
        'views/chicken_production_views.xml',
        'views/maintenance_equipment_views.xml',
        'wizard/product_wizard_views.xml',
        'wizard/bank_statement_line_wizard.xml',
        'views/real_consumption_views.xml',
        'wizard/next_phase_wizard_views.xml',
        'wizard/incubation_wizard.xml',
        'views/cost_ventilation_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'auto_install': False,
}